version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  web:
    container_name: Amber.API
    build: .
    ports:
        - "5000:80"
    environment:
      MongoDB__Host: mongo
    depends_on:
        - mongo